### PR TITLE
Register purified water bucket as fluid storage

### LINKED ISSUE #92: Travelers Backpack Support
https://github.com/Tiviacz1337/Travelers-Backpack/issues/446

### PR DESCRIPTION
**Pull request by Tiviacz1337**
Simple solution to add compatibility with Traveler's Backpack. Registered your purified water bucket as fluid storage for purified water, so it can be stored in backpack tanks. This allows for fluid to be drinkable by hose. I'll create fluid effect for purified effect that will replenish hydration. 

It'd be nice if you'd implement this feature in older versions too, althrough I don't know if you support them. 
You'd also need to create entry in lang file for your purified water fluid so it displays the name correctly in tanks, because as for now you are missing it.

Fixes #92

### CODE REVIEW

**Comment by creeloper27** [comment]
This would also probably fix #139.

**Comment by Globox1997** [comment]
Thanks for the contribution

**Comment by Tiviacz1337** [comment]
what versions will you update with this feature? @Globox1997

**Comment by Globox1997** [comment]
The latest

**Pull request merged**
