### PR TITLE
Same as last one but with a few changes

### PR DESCRIPTION
**Pull request by CJDevZ**
Last pull request was https://github.com/Globox1997/Dehydration/pull/170

I just made the compatibility optional, and it'll automatically add all optional compatibilities when BucketLib is added.

### CODE REVIEW

**Review by Globox1997 — APPROVED** [review]
Seems good to me

**Comment by CJDevZ** [comment]
When's it going to get pulled?

**Comment by Globox1997** [comment]
Currently on vacation

**Comment by cech12** [comment]
I have some additions to this PR :)
https://github.com/ColinBashful/Dehydration/pull/1

It would be great to see them in this PR :)

**Comment by cech12** [comment]
I have also another addition for this PR: fluid storages for leather flasks and copper cauldrons
https://github.com/ColinBashful/Dehydration/pull/2

Overall the fluid interactions changed a bit:
- a bucket fills only 3 levels of a campfire cauldron (because one level should be a bottle and 3 bottles are a bucket)
- campfire caudrons can now be filled with purified water
- filling and emptying of a flask can be done by right clicking a campfire cauldron (one click fills/empties  the flask to the limit of the campfire cauldron or the limit of the flask)
- bamboo pump is filling each fluid container item with an amount of 2 Bottles (fills  bottle with 1 pump, fills flask with 2 levels with 1 pump, needs 2 pumps to fill a bucket)

These changes enhance the consistency and the compatibility with other mods :)
- #139
- #148 
- #163 
- #167 
- #168

I hope I have listed everything, that has changed here :D

**Comment by Globox1997** [comment]
Have no time to look through your code so I have to trust that it is good :D
Ready to get merged or is somethin missin?

**Comment by cech12** [comment]
Nothing to add from my side :)

**Pull request merged**
