### PR TITLE
Changed thirst textures

### PR DESCRIPTION
**Pull request by RDKRACZ**
Mine are darker and the icon size is always the same to match vanilla food icons. What do you think?

### CODE REVIEW

**Comment by Globox1997** [comment]
Before you create a pull request, you could open an issue with your example and talk about it with me :) I don't see the texture, could you post it anywhere?

**Comment by RDKRACZ** [comment]
Ah, yes this seems to be better approach. I recently learned how to make pr so now I’m just open them without thinking. I can’t post the texture right now but will do in a few hours.

**Comment by RDKRACZ** [comment]
It's just my prefference.
image

**Comment by Globox1997** [comment]
If this is your personal preference you can make a resource pack for the mod quite easily :) But I will change the textures in general with the next update, love this in the middle right one, looks awesome

**Comment by RDKRACZ** [comment]
> love this in the middle right one, looks awesome

It's basically your texture with little edit :)

**Pull request closed without merging**
