### PR TITLE
Adds Compatibility and fixes a Bug or more

### PR DESCRIPTION
**Pull request by CJDevZ**
I've added compatibility with BucketLib, and now Dehydration depends on it 'cause it wouldn't work otherwise.
There still is one thing that doesn't work: you can't interact with the Copper Cauldron with any UniversalBucketItem due to the behaviorMap taking Items and you can't add instanceof UniversalBucketItem there.

I've fixed a bug where the Thirst Hud would still be visible even when in spectator.
There also seemed to be a bug where the game would crash when something gets the potion color, so I just made a null check.

### CODE REVIEW

**Comment by cech12** [comment]
I think, adding BucketLib as dependency is a really hard way to add the compatiblity^^ 
Using the FluidStorage system of Fabric would be a more suitable way and enhance the mod to be more compatible with other mods that add FluidStorages as well. :)

**Comment by CJDevZ** [comment]
I'll try using FluidStorage if possible

**Comment by CJDevZ** [comment]
> I think, adding BucketLib as dependency is a really hard way to add the compatiblity^^ Using the FluidStorage system of Fabric would be a more suitable way and enhance the mod to be more compatible with other mods that add FluidStorages as well. :)

Do you know how I may get the fluids contained in things using FluidStorage?
Or how I may change them?

**Comment by CJDevZ** [comment]
Well, now I'm trying to make BucketLib optional

**Pull request closed without merging**
