### PR TITLE
I changed some settings in the config after playing for a few minutes.

### PR DESCRIPTION
**Pull request by RDKRACZ**
This PR is more like sharing my opinions.

### CODE REVIEW

**Comment by Globox1997** [comment]
I would rather discuss default settings in the config instead of getting a pr for it^^

**Comment by RDKRACZ** [comment]
Basically, I nerfed some items thirst values and made thirst bar deplete faster.

**Comment by Globox1997** [comment]
yea I see but thats what the config will be used for inside the game :) 
Changed some settings but otherwise I don't think I need this pull request.
Why did you add the lang file in this pr because you already made another pr for it

**Comment by RDKRACZ** [comment]
>Why did you add the lang file in this pr because you already made another pr for it

I didn't, I created a new branch based on the one with this commit (because I dumb and was committing to main) but it doesn't matter cause if the previous pr gets merged this should like disappear or sth.

**Pull request closed without merging**
